name: telemt musl builds

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"
      - "3.0.*"

jobs:
  build-musl:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            artifact_name: telemt-x86_64-linux-musl
          - target: aarch64-unknown-linux-musl
            artifact_name: telemt-aarch64-linux-musl

    env:
      # Включаем статическую линковку только для musl-таргетов
      RUSTFLAGS: "-C target-feature=+crt-static"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: telemt/telemt
          ref: "3.0.3"
          fetch-depth: 0

      - name: Install musl tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build (cargo)
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Package tar.gz
        run: |
          mkdir -p out
          cp target/${{ matrix.target }}/release/telemt out/${{ matrix.artifact_name }}
          tar -C out -czf ${{
            matrix.artifact_name
          }}.tar.gz ${{ matrix.artifact_name }}
          sha256sum ${{
            matrix.artifact_name
          }}.tar.gz > ${{
            matrix.artifact_name
          }}.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ matrix.artifact_name }}.tar.gz
            ${{ matrix.artifact_name }}.tar.gz.sha256
